apiVersion: apps/v1
kind: Deployment
metadata:
  name: guptaji-tech-allianz-blue
  namespace: guptaji-tech-allianz-blue
  labels:
    app: guptaji-tech-allianz-blue
spec:
  replicas: 1
  selector:
    matchLabels:
      app: guptaji-tech-allianz-blue
  template:
    metadata:
      labels:
        app: guptaji-tech-allianz-blue
    spec:
      containers:
        - name: guptaji-tech-allianz-blue
          image: guptatrng/guptaji-tech-allianz-blue:<latestImageTag>
          env:
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: DEPLOYMENT_NAME
              value: "guptaji-tech-allianz-blue"
          ports:
            - containerPort: 5000
          resources:
            requests:
              memory: "128Mi"
              cpu: "50m"
            limits:
              memory: "256Mi"
              cpu: "125m"