apiVersion: v1
kind: Service
metadata:
  name: guptaji-tech-allianz-blue
  namespace: guptaji-tech-allianz-blue
  labels:
    app: guptaji-tech-allianz-blue
spec:
  type: LoadBalancer
  selector:
    app: guptaji-tech-allianz-blue
  ports:
    - port: 80
      targetPort: 5000
  loadBalancerIP: 35.244.38.182