FROM jenkins/inbound-agent:latest

USER root

# Install dependencies and utilities
RUN apt-get update && \
    apt-get install -y \
        apt-transport-https \
        ca-certificates \
        curl \
        sudo \ 
        gnupg \
        lsb-release \
        software-properties-common

# -------------------------------
# Install Python
RUN apt-get install -y python3 python3-pip python3-venv

# -------------------------------
# Install Docker CLI
RUN apt-get install -y docker.io

# -------------------------------
# Install Google Cloud SDK
RUN echo "deb [signed-by=/usr/share/keyrings/cloud.google.gpg] http://packages.cloud.google.com/apt cloud-sdk main" \
        | tee -a /etc/apt/sources.list.d/google-cloud-sdk.list && \
    curl -s https://packages.cloud.google.com/apt/doc/apt-key.gpg \
        | apt-key --keyring /usr/share/keyrings/cloud.google.gpg add - && \
    apt-get update && \
    apt-get install -y google-cloud-sdk

# -------------------------------
# Install kubectl
ENV KUBECTL_VERSION=v1.32.0

RUN curl -LO "https://dl.k8s.io/release/${KUBECTL_VERSION}/bin/linux/amd64/kubectl" && \
    install -o root -g root -m 0755 kubectl /usr/local/bin/kubectl && \
    rm kubectl

# -------------------------------
# Install GKE gcloud auth plugin
RUN apt-get install -y google-cloud-sdk-gke-gcloud-auth-plugin

# -------------------------------
# Cleanup to reduce image size
RUN apt-get clean && \
    rm -rf /var/lib/apt/lists/*

USER jenkins