controller:
  serviceType: LoadBalancer

  installPlugins:
    - kubernetes
    - workflow-aggregator
    - git
    - docker-workflow
    - google-oauth-plugin
    - google-kubernetes-engine

agent:
  enabled: true
  image:
     registry: ""
     repository: guptatrng/guptaji-tech-allianz-jenkins-agent
     tag: v3
  podName: jenkins-agent
  customJenkinsLabels: default
  resources:
    requests:
      cpu: "250m"
      memory: "512Mi"
    limits:
      cpu: "250m"
      memory: "512Mi"
  volumes:
    - type: HostPath
      hostPath: /var/run/docker.sock
      mountPath: /var/run/docker.sock
  runAsUser: 0 