controller:
  serviceType: LoadBalancer

  installPlugins:
    - kubernetes
    - workflow-aggregator
    - git
    - docker-workflow
    - google-oauth-plugin
    - google-kubernetes-engine

agent:
  enabled: true
  image:
     registry: ""
     repository: guptatrng/guptaji-tech-allianz-jenkins-agent
     tag: v3
  podName: jenkins-agent
  customJenkinsLabels: default
  resources:
    requests:
      cpu: "125m"
      memory: "512Mi"
    limits:
      cpu: "125m"
      memory: "512Mi"
  additionalContainers:
    - sideContainerName: dind
      image:
        repository: docker
        tag: dind
      command: dockerd-entrypoint.sh
      args: ""
      privileged: true
      resources:
        requests:
          cpu: "125m"
          memory: "512Mi"
        limits:
          cpu: "125m"
          memory: "512Mi"